In [ ]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('tt.csv')
df.head()

,Day,Time Start,Time End,Hours,Class Type,Course,Module Code,Module Title,Lecturer,Group,Block,Location,Room
0,Sun,1220,1350,1.5,Workshop,AI,*,English Profiency Class,Chudamani Rijal,Newly Admitted,Block A,Level 3,A304
1,Mon,1220,1350,1.5,Workshop,AI,*,English Profiency Class,Chudamani Rijal,Newly Admitted,Block A,Level 3,A304
2,Tue,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I2,Block A,Level 1,A106
3,Wed,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I4,Block A,Level 3,A303
4,Thu,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I3,Block A,Level 3,A301

In [10]:
df.to_csv("schedules.csv", index=False,lineterminator='\n')

In [11]:
dff = pd.read_csv('schedules.csv')
dff.head()

,Day,Time Start,Time End,Hours,Class Type,Course,Module Code,Module Title,Lecturer,Group,Block,Location,Room
0,Sun,1220,1350,1.5,Workshop,AI,*,English Profiency Class,Chudamani Rijal,Newly Admitted,Block A,Level 3,A304
1,Mon,1220,1350,1.5,Workshop,AI,*,English Profiency Class,Chudamani Rijal,Newly Admitted,Block A,Level 3,A304
2,Tue,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I2,Block A,Level 1,A106
3,Wed,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I4,Block A,Level 3,A303
4,Thu,1230,1400,1.5,Workshop,AI,*,NaN,Chudamani Rijal,I3,Block A,Level 3,A301